#9 class multi
Healthy:
  Cleaned                 : True
  Baseline45Deg           : True
  Baseline0Deg            : True
OffLocationWeld:
    Loc+10Deg             : True
    Loc+145Deg            : True
    Loc-10Deg             : True
    Loc-145Deg            : True
    Loc-2+20Deg           : True
    Loc-2+245Deg          : True
BurnThrough               : True
Porosity:
  PorosityFan             : True
  PorosityNoGas           : True
MeltBack:
  Nothces                 : True  
  Undercut                : True  
ColdWeld:
  LackofFusion            : True
BlowHole                  : True
MissingWeld               : True
ExcessiveGap:
  Gap0.5mm45Deg           : True
  Gap1mm45Deg             : True
  Gap2mm45Deg             : True
  Gap0-2mm45Deg           : True
  Gap2-0mm45Deg           : True
  ExcessiveGapWHole45Deg  : True
  ExcessiveGapWHole90Deg  : True
Crater                    : True
ShortWeld:
  ShortWelds15mm          : True
  ShortWelds20mm          : True
  ShortWelds25mm          : True
Skip                      : True
UnstableWeld              : True
WireStick                 : True
Spatter                   : True
MeltThrough:
  NoMeltThrought0Deg      : True
  NoMeltThrought45Deg     : True
  MeltThrough0Deg         : True
  MeltThrough45Deg        : True
